---
service: tachikoma-bot
frameworkVersion: '2'
provider:
  name: aws
  runtime: nodejs16.x
  environment:
    SLACK_SIGNING_SECRET: ${env:SLACK_SIGNING_SECRET}
    SLACK_BOT_TOKEN: ${env:SLACK_BOT_TOKEN}
  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action:
            - 'sqs:*'
          Resource:
            - '*'
functions:
  slack:
    handler: src/slack.handler
    events:
      - http:
          path: slack/events
          method: post
    environment:
      QUEUE_END_POINT: !Ref TachikomaQueue
  detect:
    handler: src/detect.handler
    package:
      patterns:
        - assets/**
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - TachikomaQueue
              - Arn
plugins:
  - serverless-esbuild
resources:
  Resources:
    TachikomaQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: "TachikomaQueue"
custom:
  esbuild:
    target:
      - es2020
